theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
title: ZHANHONG SU 
description: 以下是注册临床心理咨询师 Zhanhong Su 的简历.
# Set UTF-8 encoding
encoding: UTF-8

# Language settings (optional)
language: zh-CN
plugins:
  - jekyll-optional-front-matter
